### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by xiaop0817** [cherryleo/ckubeadm#1]
kubectl get nodes

The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by lzq92** [comment]
To start using your cluster, you need to run (as a regular user):

  mkdir -p $HOME/.kube
  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
  sudo chown $(id -u):$(id -g) $HOME/.kube/config
